### ISSUE TITLE
Plugins are Unintuitively Order-Sensitive

### ISSUE THREAD

**Issue by dwighthouse** [jsstyles/jss-camel-case#1]
Using the jss-camel-case plugin in conjunction with jss-extend causes rules extended from other classes to fail to be converted from camelCase to dash-case.

Example (forms.js):

    var forms = {};

    forms.button = {
        borderRadius:'6px',
        padding:'10px 15px'
    };

    forms.buttonPrimary = {
        extend:forms.button,
        background:'#f00'
    };

    module.exports = forms;

If you include the extend plugin after camelCase plugin:

    var jss = require('jss');
    jss.use(require('jss-camel-case'));
    jss.use(require('jss-extend'));

The property `borderRadius` will be converted to `border-radius`, but only for `forms.button`, not for the extending `forms.buttonPrimary`. By switching the order, the expected result occurs:

    var jss = require('jss');
    jss.use(require('jss-extend'));
    jss.use(require('jss-camel-case'));

I think this happens because the extend references the original object reference in the js file, not the actively modified style object being built up by jss. How to fix? Perhaps a way of specifying that a given plugin is expected to operate in different phases of the conversion process, and then execute those plugins in a sorted fashion:

1. Class modification (jss-extend, jss-nested)
2. Rule modification (jss-camel-case, jss-px)
3. Compatibility modification (jss-vendor-prefixer)

**Comment by kof** [comment]
You are absolutely right, need to do something about it, maybe just documentation issue of jss.

**Comment by trusktr** [comment]
Hello @kof, what's the best order for these?

```js
import jssNested         from 'jss-nested'
import jssVendorPrefixer from 'jss-vendor-prefixer'
import jssPx             from 'jss-px'
import jssExtend         from 'jss-extend'
import jssCamelCase      from 'jss-camel-case'
import jssPropsSort      from 'jss-props-sort'
```

**Comment by kof** [comment]
I think

jss-nested
jss-extend
jss-vendor-prefixer
jss-camel-case
jss-props-sort
jss-px

**Comment by kof** [comment]
Let me know if it works for you, will update the readme.

**Comment by kof** [comment]
updated, please reopen if something is still wrong.
